language: objective-c
xcode_workspace: RainyShiny.xcworkspace
xcode_scheme: RainyShiny
osx_image: xcode8.2
before_install:
  - xcrun simctl delete 22FA2149-1241-469C-BF6D-462D3837DB72 # See https://github.com/travis-ci/travis-ci/issues/7031
script:
  - set -o pipefail && xcodebuild -workspace RainyShiny.xcworkspace -scheme RainyShiny -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.2' build | xcpretty
